### ISSUE TITLE
Pushing compiled configurations to a AutomatedLab Lab

### ISSUE THREAD

**Issue by julienbosco** [dsccommunity/DscWorkshop#106]
Not sure if it's the right place for my question:

I want to push my compiled configurations to a lab built with AutomatedLab. From what I understand, `Invoke-LabDSCConfiguration` only works with powershell dsc configurations. For now, here is how I would do it:

- Build the lab
- Copy compiled files to the Hyper-V host
- Put modules in a SMB share inside the lab
- Run `Start-DscConfiguration` from my Hyper-V host
- If last step doesn't work, put compiled configurations inside the lab, and run `Start-DscConfiguration` from there.

Is there a cleaner way to do it ? If possible, I would like to make it work with a completely isolated lab (no Internet access).

Thank you 😃 

Julien

**Comment by raandree** [comment]
@julienbosco, sorry for the late reply.

You are right, ```Invoke-LabDSCConfiguration``` was designed to work with configurations and not with MOFs. But there are two other options.
1. You can use ```Copy-LabFileItem``` to make the file transfer easier.
2. You can use ```Invoke-LabCommand``` to invoke a scriptblock on the VM and copy the files it depends on as well:

```powershell
Invoke-LabCommand -ScriptBlock { Get-Content C:\ADPrep\my.ps1 } -DependencyFolderPath D:\ADPrep -ComputerName jWeb2 -PassThru
```

I hope that still helps.

**Comment by julienbosco** [comment]
Yes thank you, I've managed to make it work.
