### ISSUE TITLE
GitVersion vsix upload results in OverflowException

### ISSUE THREAD

**Issue by nyanhp** [dsccommunity/DscWorkshop#122]
The lab deployment runs into an error when uploading the GitVersion extension:
```output
08:39:47|00:00:00|00:00:00.004| Executing lab command activity: 'Uploading 'GitVersion' extension' on machines 'DSCDO01'
08:39:47|00:00:00|00:00:00.063| - Waiting for completion
{"$id":"1","innerException":null,"message":"Arithmetic operation resulted in an
overflow.","typeName":"System.OverflowException, mscorlib","typeKey":"OverflowException","errorCode":0,"eventId":0}
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebExc
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
    + PSComputerName        : DSCDO01
08:39:55|00:00:07|00:00:07.563| - Activity done
```

The same error occurs using the binary file that has been statically included in the source code for this project when using the browser to upload:
![Screenshot 2022-01-06 085235](https://user-images.githubusercontent.com/19172911/148348375-c943a4b4-fb33-49b2-bbf4-4129753e8b7e.png)

I was unable to find a download link for the vsix package, but I assume that downloading it rather than using whatever git has done to the file would solve this issue. So far, the workshop is unusable at the moment without manual intervention.

**Comment by raandree** [comment]
Thanks, @nyanhp, I have not observed this in my recent deployments. Closing this for now, please re-open if this happens again.
