### ISSUE TITLE
Build Failing on Fresh Clone

### ISSUE THREAD

**Issue by ckuewen** [dsccommunity/DscWorkshop#127]
### Problem description

Hi Folks,
i just cloned the repository and tried a build 
`git clone https://github.com/dsccommunity/dscworkshop
./dscworkshop/Build.ps1 -resolve`

The Build Failed because it couldn't find the Manifest File.
Started the Powershell with WorkingDirectory
`Start-Process powershell -WorkingDirectory C:\Repos\dscworkshop`
 and that error was resolved. I then got the issue that the modules couldn't be zipped.
Needed to do the following:
`Add-Type -Path "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.IO.Compression.FileSystem.dll"`
Then it worked.

Same Issues on a server at from customer.
How come i get these issues?

Also xSccmPrerequs and xSccmSqlSetup link old versions that are not downloaded as dependency.

### Verbose logs

```text
Error #1
===============================================================================
                        COMPILEDATUMRSOP

-------------------------------------------------------------------------------
  /./build/CompileDatumRsop
  C:\Repos\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.3\tasks\CompileDatumRsop.build.ps1:46

        Project Name               = 'DscWorkshop'
        Source Path                = 'source'
        Output Directory           = 'C:\Repos\dscworkshop\output'
        Release Notes path         = 'C:\Repos\dscworkshop\output\ReleaseNotes.md'
        Built Module Subdirectory  = 'C:\Repos\dscworkshop\output\AvoidPSPathOverlap'
        Module Manifest Path (src) = 'C:\Users\chkuewen.EUROPE\source\DscWorkshop.psd1'
ERROR: Cannot find path 'C:\Users\chkuewen.EUROPE\source\DscWorkshop.psd1' because it does not exist.
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:544 char:35
+         foreach($resolvedPath in (Resolve-Path @PSBoundParameters))
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.3\tasks\CompileDatumRsop.build.ps1:46 char:1
+ task CompileDatumRsop {
+ ~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 7 tasks, 1 errors, 0 warnings 00:00:16.1617952
Resolve-Path : Cannot find path 'C:\Users\chkuewen.EUROPE\source\DscWorkshop.psd1' because it does not exist.
At
C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:544
char:35
+         foreach($resolvedPath in (Resolve-Path @PSBoundParameters))
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\chkuew...scWorkshop.psd1:String) [Resolve-Path], ItemNotFoundE
   xception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.ResolvePathCommand



Error #2
Compressing module 'ActiveDirectoryCSDsc' to 'C:\Repos\dscworkshop\output\CompressedModules\ActiveDirectoryCSDsc_5.0.0.zip'
ERROR: Unable to find type [System.IO.Compression.ZipFile].
At C:\Repos\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.1\tasks\CompressModulesWithChecksum.build.ps1:75 char:13
+             [System.IO.Compression.ZipFile]::CreateFromDirectory($mod ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.1\tasks\CompressModulesWithChecksum.build.ps1:35 char:1
+ task CompressModulesWithChecksum {
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\Repos\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 13 tasks, 1 errors, 0 warnings 00:05:37.3333050
Unable to find type [System.IO.Compression.ZipFile].
At
C:\Repos\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.1\tasks\CompressModulesWithChecksum.build.ps1:75
char:13
+             [System.IO.Compression.ZipFile]::CreateFromDirectory($mod ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.IO.Compression.ZipFile:TypeName) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : TypeNotFound
```

### How to reproduce

`git clone https://github.com/dsccommunity/dscworkshop
./dscworkshop/Build.ps1 -resolve`

### Expected behavior

Build runs sucessfully

### Current behavior

build fails

### Suggested solution

--

### Operating system the target node is running

```text
Win11 Powershell 5.1 and Win Server 2016 PS 5.1
```

### PowerShell version and build the target node is running

```text
--
```

### Module version used

```text
Current Build
```

**Comment by raandree** [comment]
- ### Error 1
  The issue with the missing file 'DscWorkshop.psd1' was fixed 14 days ago. Can you check if you really don't see the file in the source folder, please?

- ### Error 2
  It is complaining that the type ```[System.IO.Compression.ZipFile]``` is not available which I cannot reproduce. I will have a look later why this is not failing on two of my machines but on yours.

**Comment by ckuewen** [comment]
Hi Raimund,
thanks for the response.
Error 1:
The file is available, but in the source folder. The build is searching in the wrong directory.
        Built Module Subdirectory  = '**_C:\Repos\dscworkshop\output\_**AvoidPSPathOverlap'
        Module Manifest Path (src) = _**'C:\Users\chkuewen.EUROPE\source**_\DscWorkshop.psd1'

When i start the powershell with working directory C:\Repos\dscworkshop it works. But Set-Location doesn't seem to be enough. it's weird.


Error 2:
Currently testing with another laptop of a colleague.

**Comment by ckuewen** [comment]
Error 1 is also happening on a different laptop of a colleague.
Freshly cloned repo, same issue. Module Manifest Path is wrong even though powershell is set to the correct path.

**Comment by raandree** [comment]
Thanks, Christian. I am spinning up a plain machine in Azure to exclude any previous changes on the machine and run the build again.

**Comment by raandree** [comment]
I do have a repro of this and it is weird. I have two clones of the DscWorkshop, on in the ```%USERPROFILE%``` and on on ```C:\```. Even when building the version in ```C:\```, it is complaining about the missing file in ```C:\Users\install\source\DscWorkshop.psd1```.

```
                        COMPILEDATUMRSOP

-------------------------------------------------------------------------------
  /./build/CompileDatumRsop
  C:\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.1\tasks\CompileDatumRsop.build.ps1:39

        Project Name               = 'DscWorkshop'
        Source Path                = 'source'
        Output Directory           = 'C:\dscworkshop\output'
        Release Notes path         = 'C:\dscworkshop\output\ReleaseNotes.md'
        Built Module Subdirectory  = 'C:\dscworkshop\output\AvoidPSPathOverlap'
        Module Manifest Path (src) = 'C:\Users\install\source\DscWorkshop.psd1'
ERROR: Cannot find path 'C:\Users\install\source\DscWorkshop.psd1' because it does not exist.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:544 char:35
+         foreach($resolvedPath in (Resolve-Path @PSBoundParameters))
```

As a workaround, can you delete the clone in ```%USERPROFILE%``` and clone for example into ```C:\Git```?

> **Note, after deleting the clone you should restart the PowerShell.**

**Comment by raandree** [comment]
The issue seems to be somewhere in [Sampler](https://github.com/gaelcolas/Sampler). I will do some more debugging and should come up with a fix later this afternoon.

**Comment by ckuewen** [comment]
Hi Raimund,

as mentioned, when i start the powershell with the working directory set to the dsc repo everything works.
This workaround is good enough for me at the moment.

**Comment by raandree** [comment]
Good that it works for you now, but unfortunately, something sometimes is hosed:

```
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\Users\install> cd C:\dscworkshop\
PS C:\dscworkshop> .\build.ps1
[pre-build] Starting Build Init
[pre-build] Pre-pending 'C:\dscworkshop\output\RequiredModules' folder to PSModulePath
[build] Starting build with InvokeBuild.
...
ERROR: Cannot find path 'C:\Users\install\source\DscWorkshop.psd1' because it does not exist.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Utility\Microsoft.PowerShell.Utility.psm1:544 char:35
+         foreach($resolvedPath in (Resolve-Path @PSBoundParameters))
+                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\dscworkshop\output\RequiredModules\Sampler.DscPipeline\0.1.1\tasks\CompileDatumRsop.build.ps1:39 char:1
+ task CompileDatumRsop {
+ ~~~~~~~~~~~~~~~~~~~~~~~
At C:\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
At C:\dscworkshop\build.ps1:331 char:13
+             task $workflow $workflowItem
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Build FAILED. 7 tasks, 1 errors, 0 warnings 00:00:13.0008469
```

**Comment by ckuewen** [comment]
Same for me. The only way to get it working for me is

1. Run it in VSCode Powershell Terminal
2. Start-Process powershell -WorkingDirectory <PathToDscWorkshop>

Set-Location or CD is not working. 
When you run an administrative powershell the "source\DscWorkshop.psd1" will be searched for in system32

**Comment by raandree** [comment]
Found the solution. In Sampler we are looking for the psd1 file based upon a created with ```[System.Io.Path]::GetFullPath('.')```.

The funny thing is, when calling from the folder ```C:\DscWorkshop``` the result is different based on the PowerShell host:

- PowerShell or ISE
  ```
  [System.Io.Path]::GetFullPath('.') -> C:\Users\randr
  ```
- VSCode
  ```
    [System.Io.Path]::GetFullPath('.') -> C:\DscWorkshop
  ```

I am working on a change for Sampler.

**Comment by raandree** [comment]
To remove the type not found error, this needs to be added somewhere:

```powershell
Add-Type -AssemblyName System.IO.Compression.FileSystem
```

**Comment by raandree** [comment]
This will be fixed in the next release per SynEdgy/Sampler.DscPipeline#8.
