### ISSUE TITLE
Link is dead in Task2 / Exercise1.md

### ISSUE THREAD

**Issue by LaurentLienhard** [dsccommunity/DscWorkshop#81]
In this file the link at the bottom of the page for the entire lab script is dead.

![image](https://user-images.githubusercontent.com/22775196/94521778-e2b20200-022e-11eb-923b-e5a893891170.png)

![image](https://user-images.githubusercontent.com/22775196/94521807-eba2d380-022e-11eb-94d6-99788e2e1a99.png)

**Comment by raandree** [comment]
Thanks, @LaurentLienhard. This is now fixed among other small changes in ef583ef.
